### PR TITLE
Fix missed model classes when nested within a non-annotated class

### PR DESCRIPTION
**Pull request by mcumings**
#### Ticket Summary

Fixes an issue where model classes were only being detected if the root element was annotated.

Also deletes an example unit test class.

#### Implementation Summary

Switched to a more appropriate means of detecting annotated classes.  Rather than iterating over
root elements and filtering by whether or not they are annotated with `UseStag.class` we use
the `RoundEnvironment#getElementsAnnotatedWith(UseStag.class)`.

#### How to Test

Unit test provided.

### CODE REVIEW

**Comment by mcumings** [comment]
A fast turn on this would be appreciated, if possible.

**Comment by wilrnh** [comment]
hey @mcumings I just pushed a fix for the failed check. Would you please pull it in from the latest `dev` branch please?

**Comment by mcumings** [comment]
Done!

**Comment by anthonycr** [comment]
Good catch, and glad to see that unit test 👍 I'll work on getting a 2.0.1 release out today

**Comment by mcumings** [comment]
Thanks, Anthony!

**Pull request merged**
