### PR TITLE
Genric type adapter

### PR DESCRIPTION
**Pull request by yasirmhd**
#### Ticket
Fixes Issue #92

#### Ticket Summary
public class DummyGenericClass {
HashMap<String, List> testArrayMap;
ArrayList<Map<String, T>> testListMap;
}

public class DummyInheritedClass extends DummyGenericClass {

}

Generation of TypeAdapter for DummyInheritedClass fails.

#### Implementation Summary
Changed the code in TypeUtils.getConcreteMembers to use a method resolveTypeVars. The function resolveTypeVars goes through the parameters of the generic variable type and resolves any type var to the value defined in the inherited class.

#### How to Test
Unit tests added

### CODE REVIEW

**Comment by anthonycr** [comment]
I'll review this later today, is this something you need soon as a bug fix release?

**Comment by yasirmhd** [comment]
Thanks Anthony. We will not need it right away but would like to complete the integration process, find all the bugs and then maybe request of a release if possible sometime next week.

**Comment by yasirmhd** [comment]
@anthonycr If you can kindly release this it will be of great help to us. We have not seen any other issues.

**Comment by anthonycr** [comment]
@yasirmhd I'll work on getting this out 👍

**Pull request merged**
